### ISSUE TITLE
data里面的初始化数据能不能提供一个详细的说明 有些完全不知道该去哪里申请key

### ISSUE THREAD

**Issue by zhanggenlove** [itellyou-com/itellyou-api#1]

**Comment by big-camel** [comment]
具体啥key，支付宝？geetest？

**Comment by zhanggenlove** [comment]
> 具体啥key，支付宝？geetest？
问题有点多，希望能帮我解答
1、INSERT INTO `ali_config`(`id`, `secret`) VALUES ('阿里云Key', '阿里云密钥'); 这里的key和密钥是什么
2、短信通知用的都是阿里短信服务是吧。
3、INSERT INTO `alipay_config`(`app_id`, `private_key`, `public_key`, `alipay_key`, `gateway`, `public_cert_path`, `alipay_cert_path`, `root_cert_path`, `notify_url`, `return_url`, `redirect_uri`, `is_enable`, `is_default`) VALUES ('支付宝app编号', '', '', NULL, 'https://openapi.alipay.com/gateway.do', '/cert/appCertPublicKey_xxxxx.crt', '/cert/alipayCertPublicKey_RSA2.crt', '/cert/alipayRootCert.crt', 'https://www.itellyou.com/api/pay/alipay/callback', '', 'https://www.itellyou.com/api/oauth/alipay/callback', 1, 1);
这里面的/cert/路径是本地路径吧 在工程里没找到这个路径 要自己创建的话 路径在哪个包下面？
4、INSERT INTO `collab_config`(`key`, `host`) VALUES ('default', 'wss://collab.itellyou.com');这个socket地址怎么配置？
4、INSERT INTO `geetest_config`(`id`, `key`) VALUES ('Geetest Key', 'Geetest 密钥');这里也不明白

**Comment by big-camel** [comment]
1.需要去阿里云申请 aliyun.com
2.短信，邮件都是阿里云的服务
3.这里证书只有在企业支付宝给其它支付宝转账的时候才用到，这里是提现业务需要。/cert 是放在项目的根目录，打包后也是在根目录，因为怕泄露的原因，所以需要自己建文件夹，并放置好证书
4.这个是协作编辑的服务，需要搭建 itellyou-editor-server 项目
5.geetest 是滑动验证码，需要去Geetest官网申请，免费账户，每天上限500次验证
